//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSLint.MSBuild.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSLint.MSBuild.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;{0}&lt;/h2&gt;
        ///{1}
        ///.
        /// </summary>
        internal static string HtmlFileFormat {
            get {
                return ResourceManager.GetString("HtmlFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;{0} {1}&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;{0} {1}&lt;/h1&gt;
        ///&lt;dl&gt;
        ///    &lt;dt&gt;Processed Files:&lt;/dt&gt;
        ///    &lt;dd&gt;{2}&lt;/dd&gt;
        ///    &lt;dt&gt;Violating Files:&lt;/dt&gt;
        ///    &lt;dd&gt;{3}&lt;/dd&gt;
        ///    &lt;dt&gt;Total Violations:&lt;/dt&gt;
        ///    &lt;dd&gt;{4}&lt;/dd&gt;
        ///&lt;/dl&gt;
        ///{5}
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string HtmlReportFormat {
            get {
                return ResourceManager.GetString("HtmlReportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HtmlViolationFormat {
            get {
                return ResourceManager.GetString("HtmlViolationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{0} (violations {1})
        ///{2}
        ///.
        /// </summary>
        internal static string TextFileFormat {
            get {
                return ResourceManager.GetString("TextFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///{1}
        ///({2} processed files, {3} violating files, {4} total violations)
        ///{5}.
        /// </summary>
        internal static string TextReportFormat {
            get {
                return ResourceManager.GetString("TextReportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {2} (line {0} character {1})
        ///        {3}
        ///.
        /// </summary>
        internal static string TextViolationFormat {
            get {
                return ResourceManager.GetString("TextViolationFormat", resourceCulture);
            }
        }
    }
}
